### ISSUE TITLE
Some config keys break tags when disabled

### ISSUE THREAD

**Issue by kwpugh** [Dqu1J/additionaladditions#5] opened 2021-08-15 15:09 UTC
Hello,

I'm the author of the Gobber mod and we both have mods in the Medieval Minecraft modpack.  When your mod is enabled, the ores in my mod cannot be broken with drops with vanilla or modded pickaxes.  Everything is fine if your mod is disabled.

I spent some time looking through your source code on GitHub and I do not see anything in particular that. might cause this.

Any ideas?

Regards,

Kevin

**Comment by kwpugh** [comment] 2021-08-15 17:08
I noticed this in the log after running Medieval Minecraft pack:

[11:52:53] [Worker-Main-4/ERROR]: Couldn't load tag fabric:pickaxes as it is missing following references: additionaladditions:rose_gold_pickaxe (from Additional Additions)
[11:52:53] [Worker-Main-4/ERROR]: Couldn't load tag fabric:axes as it is missing following references: additionaladditions:rose_gold_axe (from Additional Additions)
[11:52:53] [Worker-Main-4/ERROR]: Couldn't load tag fabric:hoes as it is missing following references: additionaladditions:rose_gold_hoe (from Additional Additions)
[11:52:53] [Worker-Main-4/ERROR]: Couldn't load tag fabric:shovels as it is missing following references: additionaladditions:rose_gold_shovel (from Additional Additions)

I think when yours fail, my fail as well.

**Comment by Dqu1J** [comment] 2021-08-15 17:10
Hello, Kevin!
Thanks for reporting this issue to me. Is the issue that your blocks don't drop when broken with a pickaxe with Additional Additions enabled? I am unable to reproduce that issue, with both Additional Additions and Gobber2 enabled on their latest versions, as posted on CurseForge. I used vanilla, Additional Additions and Gobber2 pickaxes, and upon breaking the Gobber Ore (gobber2:gobber2_ore), it dropped an item as it should have. I didn't use the Medieval Minecraft modpack for this, instead I used this list of Fabric mods:
* Additional Additions (2.1.0)
* Gobber2 Fabric (2.4.37)
* Lithium (0.7.3)
* Sodium (0.3.0)
The issue may be on the Medieval Minecraft side, or maybe it is intended.

**Comment by Dqu1J** [comment] 2021-08-15 17:12
The errors in the log are probably from `RoseGold` feature disabled in Additional Additions. Can you please send me your Additional Additions config? Maybe it is because of modified config file.

**Comment by Dqu1J** [comment] 2021-08-15 17:21
Yes, it is an issue with the Config! Thanks for reporting.

**Comment by kwpugh** [comment] 2021-08-15 17:27
I think the issue is that neither of us is the required=false tag for the pickaxe.json fabric tags.   If an item is disabled via config AND it is not tagged with required=false, the fabric tag reading will abort reading ANY tags from the pickaxe.json file.

I got bitten by this before with another mod.

**Comment by kwpugh** [comment] 2021-08-15 17:32
Medieval Minecraft disables RoseGold in the config and it busts the process of adding additional pickaxes to the fabric pickaxe.json tag.   I will adjust mine and you need to adjust yours, that should fix things.

**Comment by kwpugh** [comment] 2021-08-15 17:44
can you send me a test build with the new tags when you finish, so I can test with my mod to confirm the fix?

**Comment by Dqu1J** [comment] 2021-08-15 17:45
It is the latest Github Actions workflow, but I don't think it solved the issue.

**Comment by kwpugh** [comment] 2021-08-15 17:49
what did you change?  I can't see that.

**Comment by kwpugh** [comment] 2021-08-15 17:52
Oh, I see.   You need to wrap each entry, like this:  https://github.com/kwpugh/gobber_fabric-1.17/blob/1.17.1/src/main/resources/data/fabric/tags/items/pickaxes.json

**Comment by kwpugh** [comment] 2021-08-15 17:53
that way, when the tags are read, if any individual item is not actually registered, it won't stop the process of reading others.  Annoying bug in Fabric.

**Comment by kwpugh** [comment] 2021-08-15 17:55
any tool you add to any of the fabric tool tags (pickaxe.json, axe.json, etc.) that can be disabled via config, will need the wrapper tag around it.

**Comment by kwpugh** [comment] 2021-08-15 18:04
I had updated my other tool mods but forgot to update Gobber, lol.

**Comment by Dqu1J** [comment] 2021-08-15 18:04
Can you test with the latest commit?

**Comment by kwpugh** [comment] 2021-08-15 18:16
dumb question, how do I get a jar out of that?

**Comment by kwpugh** [comment] 2021-08-15 18:17
I do everything local and just push updates to GitHub.

**Comment by Dqu1J** [comment] 2021-08-15 18:17
> dumb question, how do I get a jar out of that?

[https://github.com/Dqu1J/additionaladditions/actions/runs/1133175382](https://github.com/Dqu1J/additionaladditions/actions/runs/1133175382)

**Comment by kwpugh** [comment] 2021-08-15 18:21
Bingo, that fixed it.

**Comment by Dqu1J** [comment] 2021-08-15 18:22
Is the issue resolved now?

**Comment by kwpugh** [comment] 2021-08-15 18:23
yes.  I disabled rose gold with the latest of your mod and mine and block breaking was normal.

**Comment by kwpugh** [comment] 2021-08-15 18:24
[Gobber2-Fabric-1.17.1-2.4.38.jar.zip](https://github.com/Dqu1J/additionaladditions/files/6988647/Gobber2-Fabric-1.17.1-2.4.38.jar.zip)

here is my latest if you want to try it yourself.

**Comment by Dqu1J** [comment] 2021-08-15 18:27
Closed by 771ab78

**Closed** 2021-08-15 18:26 UTC
Labels: bug, high priority
